name: Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build Binary
        run: go build -o e ./src

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./e
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Binary Release for ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
